### ISSUE TITLE
CMake build is missing numsa-config.cmake

### ISSUE THREAD

**Issue by sheepforce** [grimme-lab/numsa#11]
The project can't be found via CMake's `find_package` mechanism as the `$prefix/lib/numsa/numsa-config.cmake` file is missing. There are only the following files:

  * numsa-targets-release.cmake
  * Findmctc-lib.cmake
  * Findtest-drive.cmake
  * numsa.targets.cmake
  * xtb-utils.cmake

There is `config/config.cmake.in` which looks like the correct template, but I think it is not used anywhere?

**Comment by MtoLStoN** [comment]
Thanks for pointing that out. This happens, if I am a little bit hasty while adding the cmake support. #12 should add the configuration file.

**Comment by sheepforce** [comment]
Thank you very much, I can confirm that this has resolved the issue :sheep:
